In [3]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df = pd.read_csv('covid_toy.csv')

In [8]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
df.sample(5)

    age  gender  fever   cough       city has_covid
31   83    Male  103.0    Mild    Kolkata        No
66   51    Male  104.0    Mild    Kolkata        No
68   54  Female  104.0  Strong    Kolkata        No
58   23    Male   98.0  Strong     Mumbai       Yes
57   49  Female   99.0  Strong  Bangalore        No

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size = 0.2)

In [13]:
X_train

    age  gender  fever   cough       city
97   20  Female  101.0    Mild  Bangalore
10   75  Female    NaN    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
82   24    Male   98.0    Mild    Kolkata
43   22  Female   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
37   55    Male  100.0    Mild    Kolkata
79   48  Female  103.0    Mild    Kolkata
65   69  Female  102.0    Mild  Bangalore
68   54  Female  104.0  Strong    Kolkata
1    27    Male  100.0    Mild      Delhi

[80 rows x 5 columns]

In [14]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [15]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [16]:
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [17]:
X_train_age = X_train.drop(columns=['gender','fever', 'cough', 'city'])

X_test_age = X_test.drop(columns=['gender','fever', 'cough', 'city'])
X_train_age.shape

(80, 1)

In [18]:
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis = 1)
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis = 1)

X_train_transformed.shape

(80, 7)

In [19]:
from sklearn.compose import ColumnTransformer

In [21]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [22]:
transformer.fit_transform(X_train).shape

(80, 7)

In [23]:
transformer.transform(X_test).shape

(20, 7)