In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [3]:
df = pd.read_csv('train (2).csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [4]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [5]:
df.dropna(inplace=True)

In [6]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [7]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [8]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [10]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

**Applying Feature Construction**

In [11]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [12]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [13]:
def myfunc(num) :
  if num == 1:
    #alone
    return 0
  elif num > 1 and num <= 4:
    #small family
    return 1
  else:
    #large family
    return 2

In [14]:
myfunc(4)

1

In [15]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [16]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [17]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [18]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [19]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)

**Feature Splitting**

In [20]:
df = pd.read_csv('train (2).csv')

In [21]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [25]:
df['Title'] = df['Name'].str.split(',',expand=True)[1].str.split(',', expand=True)[0]

In [26]:
df[['Title','Name']]

,Title,Name
0,Mr. Owen Harris,"Braund, Mr. Owen Harris"
1,Mrs. John Bradley (Florence Briggs Thayer),"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,Miss. Laina,"Heikkinen, Miss. Laina"
3,Mrs. Jacques Heath (Lily May Peel),"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,Mr. William Henry,"Allen, Mr. William Henry"
...,...,...
886,Rev. Juozas,"Montvila, Rev. Juozas"
887,Miss. Margaret Edith,"Graham, Miss. Margaret Edith"
888,"Miss. Catherine Helen ""Carrie""","Johnston, Miss. Catherine Helen ""Carrie"""
889,Mr. Karl Howell,"Behr, Mr. Karl Howell"
890,Mr. Patrick,"Dooley, Mr. Patrick"

In [28]:
(df.groupby('Title').mean()['Survived']).sort_values(ascending = False)

Title
the Countess. of (Lucy Noel Martha Dyer-Edwards)    1.0
Sir. Cosmo Edmund ("Mr Morgan")                     1.0
Mrs. William (Imanita Parrish Hall)                 1.0
Mrs. William (Anna)                                 1.0
Mrs. Walter Bertram (Martha Eustis)                 1.0
                                                   ...
Mr. Kanio                                           0.0
Mr. Karl Alfred                                     0.0
Mr. Karl Gideon                                     0.0
Mr. Karl Ivar Sven                                  0.0
Mr. Leonard Charles                                 0.0
Name: Survived, Length: 803, dtype: float64

In [29]:
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

/tmp/ipykernel_2445/2254989826.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1
/tmp/ipykernel_2445/2254989826.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

In [30]:
df['Is_Married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_Married, Length: 891, dtype: int64